# Generated by Django 5.1.5 on 2026-02-26 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='AED', max_length=3)),
                ('timezone', models.CharField(default='Asia/Dubai', max_length=50)),
                ('language', models.CharField(default='en', max_length=2)),
                ('business_name', models.CharField(default='FarmCloud Livestock', max_length=255)),
                ('email', models.EmailField(default='admin@farmcloud.ae', max_length=254)),
                ('phone', models.CharField(default='+971 50 123 4567', max_length=20)),
                ('address', models.TextField(default='Dubai, UAE')),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('order_alerts', models.BooleanField(default=True)),
                ('low_stock_alerts', models.BooleanField(default=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
                'db_table': 'settings',
            },
        ),
    ]
