# Generated by Django 5.1.5 on 2026-02-25 23:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('animal_type', models.CharField(choices=[('GOAT', 'Goat'), ('SHEEP', 'Sheep')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('typical_weight_min', models.DecimalField(decimal_places=2, help_text='Minimum weight in kg', max_digits=5)),
                ('typical_weight_max', models.DecimalField(decimal_places=2, help_text='Maximum weight in kg', max_digits=5)),
            ],
            options={
                'ordering': ['animal_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('offer_type', models.CharField(choices=[('WHOLE', 'Whole Animal'), ('HALF', 'Half Animal'), ('QUARTER', 'Quarter Animal'), ('PACKAGE', 'Mixed Package'), ('CUTS', 'Specific Cuts')], max_length=20)),
                ('animal_type', models.CharField(blank=True, choices=[('GOAT', 'Goat'), ('SHEEP', 'Sheep')], max_length=10)),
                ('description', models.TextField()),
                ('details', models.TextField(blank=True, help_text='Additional details (weight range, cuts included, etc.)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='For showing discounts', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Available quantity')),
                ('image', models.ImageField(blank=True, null=True, upload_to='offers/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.CharField(help_text='Unique identification tag', max_length=50, unique=True)),
                ('animal_type', models.CharField(choices=[('GOAT', 'Goat'), ('SHEEP', 'Sheep')], max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('age_months', models.PositiveIntegerField(help_text='Age in months')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('SOLD', 'Sold'), ('PROCESSING', 'Processing')], default='AVAILABLE', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_acquired', models.DateField()),
                ('location', models.CharField(default='Main Farm', max_length=100)),
                ('health_notes', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='animals/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animals', to='inventory.breed')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'animal_type'], name='inventory_a_status_f0da4f_idx'), models.Index(fields=['tag_number'], name='inventory_a_tag_num_a5272b_idx')],
            },
        ),
    ]
