# Generated by Django 5.1.5 on 2026-02-25 23:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in UAE format', regex='^\\+?971[0-9]{9}$|^0[0-9]{9}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('emirate', models.CharField(choices=[('ABU_DHABI', 'Abu Dhabi'), ('DUBAI', 'Dubai'), ('SHARJAH', 'Sharjah'), ('AJMAN', 'Ajman'), ('UMM_AL_QUWAIN', 'Umm Al Quwain'), ('RAS_AL_KHAIMAH', 'Ras Al Khaimah'), ('FUJAIRAH', 'Fujairah')], max_length=50)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('customer_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('BUSINESS', 'Business')], default='INDIVIDUAL', max_length=20)),
                ('preferred_language', models.CharField(choices=[('EN', 'English'), ('AR', 'Arabic')], default='EN', max_length=10)),
                ('whatsapp_number', models.CharField(blank=True, help_text='If different from phone', max_length=15)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about customer')),
                ('is_active', models.BooleanField(default=True)),
                ('is_vip', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_order_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number'], name='customers_c_phone_n_cabfe1_idx'), models.Index(fields=['email'], name='customers_c_email_4fdeb3_idx'), models.Index(fields=['-last_order_date'], name='customers_c_last_or_556558_idx')],
            },
        ),
    ]
